### ISSUE TITLE
Issues Handling Biobank Data

### ISSUE THREAD

**Issue by pierreyou** [UW-GAC/GENESIS#118]
Hi,
I'm interested in running GENESIS for cross-ancestry GWAS on biobank scale data ~( > 300,000 subjects X 10,000,000 markers) but I'm having hard times at the early stages due to the huge size.
I'm trying to run the analysis on HPC using R 4.3.1 and GENESIS 2.32.0 versions. So far, I have encountered the following issues.
1) For estimating kinship coefficient, I've pruned the SNPs and ended up with ~ 300,000 SNPs. Then I used snpgdsOpen function to convert from PLINK to GDS format which was successful. Then I used snpgdsIBDKING with 10 threads  + 1000GB of RAM and after 5 days of running the job, I decided to kill it and use KING software instead which took ~ 36 hours after subsetting the subjects into 3 subsets  (3 parallel jobs with 80GB of memory and 8 cores each). 
2) After getting the output from KING (6 *kin0 files ~44 billion pairwise relationships), I used the function kingToMatrix(c(king1, king2, king3, king12, king13, king23),estimator = "Kinship") with ~ 1200GB of RAM to convert to kinship matrix and after running for ~ 8 hours, I got the following error:
```
Error in dim.data.table(x) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
Calls: kingToMatrix ... FUN -> [ -> [.data.table -> nrow -> dim -> dim.data.table
In addition: Warning messages:
1: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
2: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
3: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
4: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
5: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
6: In setattr(ans, "row.names", .set_row_names(nr)) :
  NAs introduced by coercion to integer range
Execution halted
```

Is there a way to get GENESIS to work on such big data or it wasn't designed for biobank scale analyses?
Cheers,
Pierre

**Comment by smgogarten** [comment]
You're running into a limitation in R when you try to load all the KING files into the same data.table (which happens as part of kingToMatrix): it's trying to create an index vector with > 2^31 elements, which is not allowed. Try selecting a threshold for relatedness for your analysis (e.g, 4th degree = 2^(-11/2)), and filter all your KING files to only keep pairs above this threshold before calling kingToMatrix. Then use the same value for the "thresh" input to kingToMatrix, so that the Matrix object that it creates is a sparse block-diagonal matrix.
 
For general tips on running GENESIS with biobank-scale data, you can look at the README and code for a pipeline we wrote that worked on ~150k samples: https://github.com/UW-GAC/analysis_pipeline

**Comment by pierreyou** [comment]
This is so helpful, thank you!

Cheers,
Pierre
