### ISSUE TITLE
Is it possible to test individual samples against a built model?

### ISSUE THREAD

**Issue by sstadick** [UW-GAC/GENESIS#38]
Hello!

First off, I've been really impressed with how smooth it is to get GENESIS up and running even as a bit of a novice R user. 

I have a large corpus of samples that I am generating a PC-Relate model for (millions of samples). I was wondering if it is possible to do the following things:

- Add to the kinbtw model in batches? (over time, adding more samples)
- Test an individual sample pairwise agains all samples in the model for kinship?

Looking at the code, I'm not seeing a way to do this. Am I missing anything built in? If not built in, do you think there is a path of adding it? (I'm happy be the implementor if needed).

**Comment by mconomos** [comment]
Hello! 

I'm glad to hear that you have had a good experience with GENESIS. The questions you asked have complicated answers, but I'll try to address them.

**Add to the kinBtwn results in batches?**

The short answer is yes, there is a way to run the PC-Relate analysis in batches. There are a few steps to this though. 

You may want to look at [this pcrelate pipeline script](https://github.com/UW-GAC/analysis_pipeline/blob/master/pcrelate.py) on our UW-GAC analysis pipeline github repo. That pipeline script uses 4 different R scripts also contained in that github repo and several functions from with GENESIS. Here is a summary of what you would need to do:

1) Calculate the regression parameters (betas) that will be used to estimate the individual specific allele frequencies at each variant. This is done using the `calcISAFBeta` function in GENESIS. This step only requires data for the samples you want to use to train the model; i.e. the `training.set` when you run `pcrelate`; this is usually a set of mutually unrelated individuals, but it could also be a set of reference samples. Inputs are the genotype data as a GDS iterator object, a matrix of PCs you want to use for ancestry adjustment, and the list of sample IDs for these training samples. See [this R script](https://github.com/UW-GAC/analysis_pipeline/blob/master/R/pcrelate_beta.R) for example code.

2) Run the PC-Relate analysis in batches defined by "sample blocks." This is done using the `pcrelateSampBlock` function in GENESIS (several times). This allows you to break up the PC-Relate analysis into multiple jobs by analyzing samples in pairs of blocks. Inputs are the matrix of betas calculated in step 1 above, genotype data as a GDS iterator object, a list of sample IDs for the samples in block 1, a list of sample IDs for the samples in block 2, and the matrix of PCs for all samples in either block. Because you need to estimate all pairwise relationships in your entire sample set, you'll need to run one analysis for each pair of blocks, including each block with itself; e.g. with 3 blocks: an analysis of B1 and B2, another of B1 and B3, B2 and B3, B1 with itself, B2 with itself, and B3 with itself.  See [this R script](https://github.com/UW-GAC/analysis_pipeline/blob/master/R/pcrelate.R) for example code. 

3) Combine the PC-Relate results from all jobs in step 2 and do some post processing of results. See [this R script](https://github.com/UW-GAC/analysis_pipeline/blob/master/R/pcrelate_correct.R) for example code. Note that the kinBtwn file can become very large in a large sample since it has a row for all pairs. To keep that file more manageable, you may want to exclude pairs with kinship below some threshold, which is handled by the `kin.thresh` parameter in the script. This script also contains code for transforming the kinSelf and kinBtwn data.frames into a kinship matrix with the `pcrelateToMatrix` function from GENESIS. 

4) Make some plots of the results. [This R script](https://github.com/UW-GAC/analysis_pipeline/blob/master/R/kinship_plots.R) has some code for making hexbin plots of the PC-Relate results. Not required, but helpful for visualizing the output.


Typically, when running PC-Relate, we've assumed that you have your full set of samples to perform the analysis on. However, your question specifically asked about **adding more samples over time**. Assuming you don't want to re-run the whole process each time you get new samples, this adds a bit of complexity, but I think is doable. One thing to keep in mind is that you would need to keep the structure of your ancestry PCs consistent across time. That means that you would want to create your ancestry PCs on some initial set of data, and not update them as you get more samples. This could be your first batch of unrelated samples, or perhaps a set of reference samples with known ancestry. Each time you got a new batch of samples, you would need to get their PC values by projecting them onto that original PC space (rather than running a new PCA). This can be accomplished with the `pcair` function in GENESIS: specify your initial set of unrelated samples defining the PC space as the `unrel.set` (don't use a `kinobj` or `divobj`), and all the other samples will be projected onto that PC space. Keep in mind that not updating the PCA runs the risk of not capturing ancestry structure that is present in the new samples, but was not present in the original. 

If you do take this approach, then you would still use the same regression betas for ancestry adjustment in PC-Relate for the new samples, so you would not need to re-run step 1 above. You would need to re-run step 2 for all new pairs of sample blocks, and then run step 3 on the entire set of results from all sample block pairs. 


**Test an individual sample pairwise agains all samples in the model for kinship?**

I think you could accomplish this by specifying a sample as its own block in step 2 above. Then run several analyses with the single sample block and all other samples broken into several blocks. You wouldn't run the cross sample blocks that didn't include your sample of interest.


I realize this is a lot of information. Hopefully it is helpful. If you have further questions, I'd be happy to attempt to answer them.  

Matt

**Comment by sstadick** [comment]
Hi Matt!

Thank you for the detailed answer! This is all incredibly helpful. I need to do some investigating / deep diving on what you've provided, but this is definitely solved!

**Comment by cindywen96** [comment]
Thanks for the replies! They are very helpful. My question is what is the best way to deal with large genotype data, i.e. imputed ~50m SNPs. I'm using `GenotypeBlockIterator` to build iterators as in step 1, except that I'm working with SNP, not sequence array GDS file. Is there any way to speed up the "Calculating Indivdiual-Specific Allele Frequency betas" step?

**Comment by smgogarten** [comment]
@cindywen96 I recommend LD pruning before running PC-AiR or PCRelate, which should reduce the number of SNPs to something manageable. See the [vignette](http://bioconductor.org/packages/release/bioc/vignettes/GENESIS/inst/doc/pcair.html#ld-pruning) for an example.

**Comment by cindywen96** [comment]
Thanks for the quick reply! Yes, I've already pruned SNP using PLINK (it's imputed data). I've successfully run PC-AiR and I got the KING matrix too. The SNP block iterator step is very slow though and I don't see a multi-thread/core option.
