### ISSUE TITLE
 assocTestSingle results:  MAC, n.obs and freq don't match.

### ISSUE THREAD

**Issue by yanglipmed** [UW-GAC/GENESIS#60]
use "1-MAC/n.obs" to calculate SNP freq, but it doesn't match the freq given by assocTestSingle result.

row.id--variant.id--chr--pos--n.obs----freq----MAC----Score
486612    16055342   5   2648696  6387 0.9999198   1 -0.9808342238
32370     16055799   5   2665352  6387 0.9999153   1 -0.9951444874
243629    16142912   5   6575722  6387 0.9999915   0 -0.1023526695
457635    16175052   5   8172258  6387 0.9999654   0 -0.2336916838
466436    16175140   5   8176852  6387 0.9999654   0 -0.2336916838
188639    16192362   5   8995817  6387 0.9999416   1 -0.5098825422
131844    16211794   5   9978068  6387 0.9999090   1 -0.9181567810
3839139   16694315   5  34766540  6387 0.9999144   1 -0.9661750655
1469144   16716945   5  35962594  6387 0.9999154   1 -0.9703244084
1584144   16717060   5  35970516  6387 0.9999150   1 -0.9702497538
4554485   18455030   5 133261208  6387 0.9999555   1 -0.5108373173
4661758   18455137   5 133268025  6387 0.9999621   0 -0.4650721894
4289491   18464765   5 133842935  6387 0.9999313   1 -0.7213551748
4711802   18465187   5 133871022  6387 0.9999249   1 -0.8912234380
2261764   18472737   5 134354541  6387 0.9999988   0 -0.0123795277
4912514   18475388   5 134496277  6387 0.9999060   1 -0.9474345675
1979497   18492455   5 135394341  6387 0.9999146   1 -0.9584221596
2162511   18492638   5 135403773  6387 0.9999178   1 -0.9663698679
4565498   18505041   5 136104042  6387 0.9998915   1 -1.0145696174
2472517   18527948   5 137531525  6387 0.9992340  10 -1.4651801670
1762529   18567238   5 140169487  6387 0.9999941   0 -0.0702220428
859527    18641335   5 144213292  6387 0.9999209   1 -0.9724937863
2770522   18643246   5 144310206  6387 0.9999133   1 -0.9588007179

**Comment by mconomos** [comment]
Hello. Could you please provide some additional information:

- what version of GENESIS are you using?
- is this human data? is it diploid? If it is, then freq = 1 - MAC/(2*n.obs) since each person carries two alleles. (Though your numbers still don't match). 
- Are you using imputed dosage data?
- Could you run `print()` on your gds data object and post the results?

**Comment by yanglipmed** [comment]
1. GENESIS version is 2.18.0 in R 4.0.2

2. It is human data. The original data is already in gds format. I used SNPRelate package to read it, then analyze them in GENESIS, as I need to use mixed model. Most SNPs are bialleic:
gds=snpgdsOpen('xxxx.gds')
snpgdsSummary(gds)

results:
Some of 'snp.allele' are not standard (e.g., A/<CN0>).
The file name: xxxxx/chr22.gds
The total number of samples: 10262
The total number of SNPs: 711309
SNP genotypes are stored in SNP-major mode (Sample X SNP).
The number of valid samples: 10262
The number of biallelic unique SNPs: 666027   # this means some SNPs are not biallelic

3. The data is imputed.  I think it is not dosage data. Seems probability.
read.gdsn(index.gdsn(gds,path='genotype'),start=c(1,1), count=c(6,8))

results:       [,1]  [,2]  [,3] [,4] [,5] [,6] [,7]  [,8]
[1,] 1.998 1.998 2.000    2    2    2    2 1.989
[2,] 1.997 2.000 1.997    2    2    2    2 1.993
[3,] 1.995 2.000 1.995    2    2    2    2 1.991
[4,] 1.990 1.997 2.000    2    2    2    2 1.993
[5,] 2.000 2.000 2.000    2    2    2    2 1.995
[6,] 1.998 1.997 2.000    2    2    2    2 1.938

4. print(gds)
results:
File: xxxxx/chr22.gds (27.2G)
+    [  ]
|--+ sample.id   { Int32 10262 LZMA_ra(29.6%), 11.9K }
|--+ snp.id   { Int32 711309 LZMA_ra(3.88%), 107.7K }
|--+ snp.position   { Int32 711309 LZMA_ra(30.2%), 839.1K }
|--+ snp.chromosome   { UInt8 711309 LZMA_ra(0.04%), 257B }
|--+ snp.allele   { Str8 711309 LZMA_ra(15.8%), 463.1K }
\--+ genotype   { Float32 10262x711309, 27.2G } *

**Comment by mconomos** [comment]
Thanks for the additional info. I think the apparent discrepancy comes from the fact that the data is imputed, so not all genotype values are integers. With imputed data, MAC is somewhat poorly-defined, but GENESIS rounds to the nearest integer MAC based on the calculated allele frequency. Internally, GENESIS does the following to compute freq and MAC for non-sex chromosomes (see the `.alleleFreq` internal function):
```
count <- colSums(geno, na.rm=TRUE)
nsamp <- .countNonMissing(geno, MARGIN = 2)
freq <- count/(2*nsamp)
mac <- round(pmin(count, 2*nsamp - count))
```
The rounding in the `mac` calculation is there because `count` will be a non-integer with imputed data. I spot checked a couple of the rows from the results you sent, and when I perform that `mac` calculation using the reported `freq`, `n.obs` (in place of `nsamp`), and round, I get the same answer.

**Comment by yanglipmed** [comment]
Thanks. I checked it. You are right.
