### ISSUE TITLE
Outdated pcair() call in vignette

### ISSUE THREAD

**Issue by pamelarussell** [UW-GAC/GENESIS#73]
I believe [this](https://github.com/UW-GAC/GENESIS/blob/57c446cbe90f2702cd578eee573946cd0cca772b/vignettes/pcair.Rmd#L160) `pcair()` call in the vignette is outdated, as the S4 method for `GenotypeData` does not take arguments `kinobj`, etc.

[This workflow](https://github.com/UW-GAC/GENESIS/blob/556d875c8b988fea9c65b8ebf820e43651c0c88f/tests/testthat/test_pcair.R#L9) from your test is working for me.

**Comment by smgogarten** [comment]
The `GenotypeData` method can take `kinobj`, etc. arguments. See [this test](https://github.com/UW-GAC/GENESIS/blob/master/tests/testthat/test_pcair.R#L42) further down in the file you cited. The man page is confusing on this point, because it shows a single argument for many of the methods, but what they are really doing is passing all their arguments (including `kinobj`) on to the `gds.class` method. I will try to clarify that in the documentation.

The caveat is that it currently only works if the `GenotypeData` object was created with `GdsGenotypeReader` object. Adding the option to use a `MatrixGenotypeReader` is on my to-do list.

**Comment by smgogarten** [comment]
`MatrixGenotypeReader` support and improved documentation added in 6642e86.
